### ISSUE TITLE
Adjust database column used to print class name

### ISSUE THREAD

**Issue by vanteer** [event-cell/core#37]

**Comment by vanteer** [comment]
@myberlina, what is your preferred column for class name?

**Comment by myberlina** [comment]
C_I29  seems to be the name in sqlite.

The original email about the changes I made at the start of last year is:

Had a bit of a problem with the new class names, they are much longer (longest is 43 chars)
 Also the text fields have a fixed max in the timing software (at least I could not find
where
to change them), however you can rename and activate/deactivate them.

The solution I have settled on was to re-purpose some other field.
Most of the text fields are 30 characters, however there is one that is 60 and another 80.
DK had been using them for other things, so I have had to do a small shuffle.  I think this
will impact your code as I am only changing the titles of the fields.  The changes are:


Field 10  name changed from  "Class"  to   "Too Short", and no longer used
    I think you are addressing it as  C_SERIE

Field 27  name changed from  "No. in class"  to  "Record"

Field 29  name changed from  "Record"  to  "Class"


Looking at your code, you seem to be using  C_SERIE, but if not set use C_I29

changing that from not set to  not set or numeric would be good

**Comment by vanteer** [comment]
To easy, I'll make that adjustment tonight

**Comment by vanteer** [comment]
```
Field 10 name changed from "Class" to "Too Short", and no longer used
I think you are addressing it as C_SERIE
```
No longer accessed

`Field 27 name changed from "No. in class" to "Record"`

Record seems to be field C_TEAM
No changes performed

`Field 29 name changed from "Record" to "Class"`
I_29 now used for class exclusively

**Comment by vanteer** [comment]
@myberlina, can you confirm what field you want to use for record.

Database for event # 072 uses C_TEAM for record.  Is this OK?

**Comment by myberlina** [comment]
I don't think the Record field is all that useful anymore

From what I can gather, it was just a free text field that DK added for the certificates.  At the end of the event, he would type the word "Record" in there manually, he then had a report in Msports that created a spread sheet for the certificate mail merge.

I think your new end-of-day-results spreadsheet now generates the certificate spread sheet, and sets the record text.

The C_TEAM field it titled  "Old Record", and has the time of the Old record.  I have not changed that.

**Comment by vanteer** [comment]
Ah, yeah good point.  I'll clean up.

**Comment by vanteer** [comment]
Actually C_TEAM is still used to record the current record for the class that a competitor is in.  Without this field the code cannot show the record on the timing board, nor if a run beat the previous record.  The end of day results prints "record" when the run is lower than this amount as well.

I started to write a database to track records outside of the timing software (you can search for it), but not sure introducing state is the right thing to do.  

I'm going to close this for now, but open a new issue.
